### ISSUE TITLE
HA Pad - No way of dragging text from bottom of left hand pane to right hand pane.

### ISSUE THREAD

**Issue by maboa** [hyperaudio/hyperaudio-drupal8#2]
Since the drop-zone for the text is towards the top of the right hand pane - there is no way of moving text from the left to the right when the left-hand text resides below a certain point. (At least with a track pad, scrolling while dragging isn't an option).

**Comment by Laurian** [comment]
CSS issue, will ask @piotrf on how to have "columns"

**Comment by piotrfonte** [comment]
Anywhere I can play with it without running locally?
